version: "3.3"

services:
  postgres:
    image: postgres:latest
    ports:
      - 10432:5432
    environment:
      - POSTGRES_USER=cash_management_service
      - POSTGRES_DB=cash_management_service
      - POSTGRES_PASSWORD=cash_management_service
  cash_management_service:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/cash_management_service
      - DATABASE_USER=cash_management_service
      - DATABASE_PASSWORD=cash_management_service


